<style>
<!--
.button {cursor: pointer;padding: 5px;background-color: #6F6E81;color: #FFF;border: 0px none;outline: 0px none;}
-->
</style>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESDocumentsMetadata/js/addoredit.js"></script>
<div style="padding-top: 30px;">
		<form id="addDataForm" method="post">
		    <input type="hidden" name="stageId" id="stageId" value=""/>
			<input type="hidden" name="isSystem" id="isSystem" value="1"/>
			<div class="estransfer">
			<ul>
				<li>
					<span>字段名称<font color="red" size="3">*</font></span>
					<input type="text" name="name" id="name" verify="unspecial/20/1/0" value=""  />
				</li>
				<li>
					<span>字段代码<font color="red" size="3">*</font></span>
					<input type="text" name="code" id="code" verify="china-english/20/1/0" value=""  />
				</li>
				<li>
					<span>档案元数据</span>
					<input type="text"  id="esidentifier" name="esidentifier" class="selectInput"
						readonly="readonly"  value=""  title ="点击选择"/>
					<input type="hidden" id="metaDataId" name="metaDataId"  value=""  />
				</li>
				<li>
					<span>字段类型<font color="red" size="3">*</font></span>
						<select name="type" id="type"  class="inputselect" >
							<option value="TEXT" >文本</option>
							<option value="NUMBER" >数值</option>
							<option value="DATE" >日期</option>
							<option value="FLOAT" >浮点</option>
							<option value="TIME" >时间</option>
							<option value="BOOL" >布尔</option>
						</select>
				</li>
				<li>
					<span>字段长度<font color="red" size="3">*</font></span>
					<input type="text"  name="toLength" id="toLength" verify="number/11/1/0" value="40"  />
				</li>
				<li>
					<span>小数点长度</span>
					<input type="text"  name="dotLength" id="dotLength" verify="number/11/0/0" value=""  />
				</li>
				<li>
					<span>是否为空<font color="red" size="3">*</font></span>
					<span>
					<input type="radio" name="isNull" style="width: 13px" id="is" value="0" checked ><label style="display: inline;" for="is">是</label>
					</span>
					<span>
					<input type="radio" name="isNull" style="width: 13px" id="no" value="1" ><label style="display: inline;" for="no">否</label>
					</span>
				</li>
				<li>
					<span>默认值</span>
					<input type="text" name="defaultValue" id="defaultValue" verify="unspecial/200/0/0"  value=""  />
				</li>
			</ul>
		  </div>
		</form>
	</div>
<script type="text/javascript">
//编辑的时候初始化默认值的校验规则
$(document).ready(function(){
	$("#stageId").val($("#treenodeid").val());
});

</script>