<style type="text/css">
<!--
#userRole .userList{ width:190px; height:230px; float:left; margin-top:10px; border:1px solid #ccc; overflow-y:scroll;}
-->
</style>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESDocumentsMetadata/js/jumpwindow.js"></script>

<div id='userRole'>
  <input type="hidden" id="stageId" value='<?php echo $stageId; ?>'>
  <input type="hidden" id="tagtexts" value='<?php echo $tagtexts; ?>'>
  <input type="hidden" id="id" value='<?php echo $id; ?>'>
  <div id='' class='useLis'>
    <div class='searchRole'>
      <input type='text' id='one' class='searchusername' value='' onKeyUp="show(this.value,'left');"/>
	  <input type='image' id='' class='searchuserbutton' src='<?php echo $tplPath;?>/ESDocumentsMetadata/img/search.bg.gif' />
	</div>
    <ul id='listRole' class='userList'><?php echo $left; ?></ul>
  </div>
	<div id='esbutton' class='selBut'>  
	<div id="extrarule" class="zerorule" ><p  class='spa' style="font-size:10px;">连接符</p><form id="docNoField"><input  type="text" name="comlen" class="inpu" verify="unspecial-/1/0/0"/></form><button id="chan" style="width:35px;">=></button></div>
		<span id="estop" class="estop" title='置顶'></span>
		<span id="esup" class="esup" title='上移'></span>
		<span id="esleft" class="esleft" title='左移'></span>
		<span id="esright" class="esright" title='右移'></span>
		<span id="esdown" class="esdown" title='下移'></span>
		<span id="esbottom" class="esbottom endspan" title='置底'></span>
	</div>
	<div id='' class='useLis'>
		<div class='searchRole'>
			<input type='text' id='two' class='searchusername'  value='' onKeyUp="show(this.value,'right');"/>
			<input type='image' id='' class='searchuserbutton' src='<?php echo $tplPath;?>/ESDocumentsMetadata/img/search.bg.gif' />
		</div>
		<ul id='useRole' class='userList'></ul>
	</div>
</div>
