<link href="<?php echo $tplPath?>/ESVirtualRepository/css/index.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESVirtualRepository/js/index.js"></script>

<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>
<script type="text/javascript">
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"虚拟3D库房", content:"#esmenu,#esone,#eslist"});
});
</script>
<div id="eslist" class = "essContainer">
    <img class="cutImg" id="i1" style="width: 100%;" src="<?php echo $tplPath?>/ESVirtualRepository/img/1.png">
    <div class="cutMap" id="b1" style="position:absolute;border: #000 1px solid;right: 35px;top: 417px;height: 18px;width: 213px;cursor:pointer;"></div>
    <img class="cutImg" id="i2" style="display:none;width: 100%;" src="<?php echo $tplPath?>/ESVirtualRepository/img/2.png">
    <div class="cutMap" id="b2" style="display:none;position:absolute;border: #000 1px solid;left: 30px;top: 148px;height: 22px;width: 100px;cursor:pointer;"></div>
    <div class="cutMap" id="b3" style="display:none;position:absolute;border: #000 1px solid;left: 40px;top: 180px;height: 140px;width: 120px;cursor:pointer;"></div>
    <img class="cutImg" id="i3" style="display:none;width: 100%;" src="<?php echo $tplPath?>/ESVirtualRepository/img/3.png">
    <div class="cutMap" id="b4" style="display:none;position:absolute;border: #000 1px solid;right: 40px;top: 156px;height: 25px;width: 62px;cursor:pointer;"></div>
    <div class="cutMap" id="b5" style="display:none;position:absolute;border: #000 1px solid;left: 380px;top: 330px;height: 190px;width: 60px;cursor:pointer;"></div>
    <img class="cutImg" id="i4" style="display:none;width: 100%;" src="<?php echo $tplPath?>/ESVirtualRepository/img/4.png">
    <div class="cutMap" id="b6" style="display:none;position:absolute;border: #000 1px solid;right: 45px;top: 156px;height: 25px;width: 62px;cursor:pointer;"></div>
    <div class="cutMap" id="b7" style="display:none;position:absolute;border: #000 1px solid;left: 620px;top: 420px;height: 80px;width: 140px;cursor:pointer;"></div>
    <img class="cutImg" id="i5" style="display:none;position:absolute;left: 145px;top: 156px;" src="<?php echo $tplPath?>/ESVirtualRepository/img/6.png">
    <div class="cutMap" id="b8" style="display:none;position:absolute;border: #000 1px solid;left: 1014px;top: 156px;height: 25px;width: 25px;cursor:pointer;"></div>
</div> 