<style type="text/css">
.selectztree {
	margin-top: 10px;
	border: 1px solid #808080;
	background: #f0f6e4;
	width: 220px;
	height: 250px;
	overflow-y: scroll;
	overflow-x: auto;
}
</style>
<div id="filterContents" style="padding: 20px; padding-bottom: 40px;">
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span> <span
			class='w90 w14090 hei30'>比较符</span> <span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span> <span
			class='w90 w14090 hei30'
			style="text-align: center; margin-right: 0px; width: 55px;">添加行</span></span>
		<span class='w90 w14090 hei30'
			style="text-align: center; margin-right: 0px; width: 60px;">删除行</span></span>
	</p>
	<div id='contents'>
		<?php for($fly=1;$fly<6;$fly++){ ?>
		<p class='contbox creatediv' style="overflow: hidden;"
			indx="<?php echo $fly; ?>">
			<select class='w140 w14090 hei20 filedname'>
				<option value=''>请选择</option>
				<option value='name'>工作流名称</option>
				<option value='typeNo'>收集范围</option>
				<option value='status'>状态</option>
				<option value='describtion'>描述</option>
				<option value='creater'>创建人</option>
				<option value='createtime'>创建时间</option>
				<option value='modifyer'>修改人</option>
				<option value='modifytime'>修改时间</option>
				<option value='version'>版本</option>
			</select> <select class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select> <input type='text' class='w140 w14090 hei20 filedvalue'
				value="" /> <input type='text'
				class='w140 w14090 hei20 selfiledvalue'
				id="filedvalue<?php echo $fly; ?>" style="display: none;"
				readonly="readonly" value="" /> <select id=''
				class='w14090 w90 hei20 relationship'>
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select> <a class='newfilter'></a><a class='delfilter'></a>
		</p>
		<?php }?>
	</div>
	<br />
	<div id="menuContent" class="menuContent"
		style="display: none; position: fixed;">
		<ul id="treeDemo" class="ztree selectztree"
			style="margin-top: 0; width: 312px; height: 250px; color: #000"></ul>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#contents .filedname").die().live('change',function(){
		if($(this).val()=="typeNo"){
			$(this).closest("p").find(".filedvalue").hide();
			$(this).closest("p").find(".selfiledvalue").show();
			$(this).closest("p").find(".selfiledvalue").val("");
			var Setting = {
					chkStyle:"radio",
					inputId:"filedvalue"+$(this).closest("p").attr("indx"),//触发事件的id
					treeDIVId:"menuContent",
					treeUlId:"treeDemo",
					selectId:"beautySelect",//可选
					url:$.appClient.generateUrl({ESDocumentsCollection : "getTree"}, 'x')
				};
			$.treeSelected._onCheck = function(e, treeId, treeNode) {
				var zTree = $.fn.zTree.getZTreeObj(Setting.treeUlId);
				nodes = zTree.getCheckedNodes(true);
				var d = "";
				var n="";
				for (var i=0, l=nodes.length; i<l; i++) {
					d += nodes[i].code + ",";
					n += nodes[i].name + ",";
				}
				if (n.length > 0 && d.length>0 ) {
					d = d.substring(0, d.length-1);
					n = n.substring(0, n.length-1);
				}
				$("#"+Setting.inputId).val(n);
				$("#"+Setting.inputId).prev("input").val(d);
			};
			$.treeSelected._init(Setting);
		}else{
			$(this).closest("p").find(".filedvalue").show();
			$(this).closest("p").find(".filedvalue").val("");
			$(this).closest("p").find(".selfiledvalue").hide();
		}
	});
});
</script>