<!-- xiewenda -->
<form id="addRegulation" action=""	method="post">
<div class="estransfer">
<ul>
<li><span>编号<font color="red" size="3">*</font></span><input  type="text" name="no"  verify="desc/20/1/0" value=""><input type="hidden" name="itemId"    value="1"  ></li>
<li><span>中文名称<font color="red" size="3">*</font></span><input type="text" name="chineseName"   verify="china/100/1/0"  value=""></li>
<li><span>英文名称</span><input type="text" name="englishName"   verify="englishname/100/0/0"  value=""></li>
<li><span>发布时间<font color="red" size="3">*</font></span><input type="text" name="publishTime"  class="Wdate" verify="date/100/1/0"  value=""></li>
<li><span>附件<font color="red" size="3">*</font></span><input type="button" id="fileUp" value='附件上传' class='fileUpButton' style="height:25px"/>
</li>
</ul>
</div>
<div id="loadfile" style="margin-left:150px"></div>
</form>