
<div id='filterContents' style='padding:20px;'>
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span>
		<span class='w90 w14090 hei30'>比较符</span>
		<span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">添加行</span></span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">删除行</span></span>
	</p>
	<div id='contents'>
		<?php for($fly=1;$fly<6;$fly++){ ?>
		<p class='contbox creatediv'  style="overflow:hidden;">
			<select class='w140 w14090 hei20 filedname'>
				<option value=''>请选择</option>
				<option value='no'>编号</option>
				<option value='chineseName'>中文名称</option>
				<option value='englishName'>英文名称</option>
				<option value='publishTime'>发布时间</option>
			</select>
			<select  class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue' />
			<select id='' class='w14090 w90 hei20 relationship'>
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<a class='newfilter'></a><a class='delfilter'></a>
		</p>
		<?php }?>
	</div>
</div>
<script type='text/javascript'>
var _widget = {
		change : function (that){
			if(that.value == "publishTime"){
			$(that).parent().find('.filedvalue').addClass("Wdate");
			}else{
			$(that).parent().find('.filedvalue').removeClass("Wdate");
			$(that).parent().find('.filedvalue').removeAttr("readonly");
			$(that).parent().find('.filedvalue').val("");
			}
		}
};
$('.filedname').die().live('change',function (){
		_widget.change(this); // 当前下拉框值和要替换的DIV内容
});

$('.Wdate').live('click', function (){
		WdatePicker({dateFmt:'yyyy-MM-dd'});
});
</script>