<link href="<?php echo $tplPath;?>/ESStoreroom3D/css/index.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $tplPath; ?>/ESStoreroom3D/flex/history/history.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $tplPath;?>/ESStoreroom3D/js/index.js" type="text/javascript"></script>
<script src="<?php echo $tplPath; ?>/ESStoreroom3D/flex/AC_OETags.js" type="text/javascript"></script>
<script src="<?php echo $tplPath; ?>/ESStoreroom3D/flex/history/history.js" type="text/javascript"></script>

<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>

<script  type="text/javascript">
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"3D库房", content:"#esstore"});
	$("#esstore").css({"background-color":"white","margin-top":"10px"});
	setPageSize();
});
function setPageSize(){
	$("#esstore").css("width",$(document).width() - 140);
	$(".store3dBody").css("height",$(document).height() - 140);
	var estabW=$("#esstore").css("width").split("px")[0]-230;
	$("#estabs").css("padding-left",estabW/2-54).css("width",estabW/2+54);
	$(".seporateLine").css("width",estabW);
	$(".seporateArea").css("width",estabW);
}
</script>
<div id="esstore" class="essContainer">
<div style="width: 100%; float: left;" id="store3dBody">
	<input type="hidden" name="url3D" id="url3D"
		value="<?php echo $tplPath; ?>" />
	<noscript>
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
			id="esoais" width="100%" height="100%"
			codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">
			<param name="movie"
				value="<?php echo $tplPath; ?>/ESStoreroom3D/flex/esoais.swf" />
			<param name="quality" value="high" />
			<param name="bgcolor" value="#ffffff" />
			<param name="allowScriptAccess" value="sameDomain" />
			<embed src="<?php echo $tplPath; ?>/ESStoreroom3D/flex/esoais.swf"
				quality="high" bgcolor="#ffffff" width="100%" height="100%"
				name="esoais" align="middle" play="true" loop="false" quality="high"
				allowScriptAccess="sameDomain" type="application/x-shockwave-flash"
				pluginspage="http://www.adobe.com/go/getflashplayer">
			</embed>
		</object>
	</noscript>
</div>
</div>
<script type="text/javascript">
var requiredMajorVersion = 9;
var requiredMinorVersion = 0;
var requiredRevision = 124;
var hasProductInstall = DetectFlashVer(6, 0, 65);
var hasRequestedVersion = DetectFlashVer(requiredMajorVersion, requiredMinorVersion, requiredRevision);
var url=$("#url3D").val()+"/ESStoreroom3D/flex/";
if ( hasProductInstall && !hasRequestedVersion ) {
	var MMPlayerType = (isIE == true) ? "ActiveX" : "PlugIn";
	var MMredirectURL = encodeURI(window.location);
 document.title = document.title.slice(0, 47) + " - Flash Player Installation";
 var MMdoctitle = document.title;
	AC_FL_RunContent(
		"src", url+"playerProductInstall",
		"FlashVars", "MMredirectURL="+MMredirectURL+'&MMplayerType='+MMPlayerType+'&MMdoctitle='+MMdoctitle+"",
		"width", "100%",
		"height", "100%",
		"align", "middle",
		"id", "esoais",
		"quality", "high",
		"bgcolor", "#ffffff",
		"name", "esoais",
		"allowScriptAccess","sameDomain",
		"type", "application/x-shockwave-flash",
		"pluginspage", "http://www.adobe.com/go/getflashplayer"
	);
} else if (hasRequestedVersion) {
	AC_FL_RunContent(
			"src", url+"esoais?http://127.0.0.1/essoaapp/messagebroker/amf",
			"width", "100%",
			"height", "100%",
			"align", "middle",
			"id", "esoais",
			"quality", "high",
			"bgcolor", "#ffffff",
			"name", "esoais",
			"allowScriptAccess","sameDomain",
			"type", "application/x-shockwave-flash",
			"pluginspage", "http://www.adobe.com/go/getflashplayer"
	);
} else {
 var alternateContent = 'Alternate HTML content should be placed here. '
	+ 'This content requires the Adobe Flash Player. '
	+ '<a href=http://www.adobe.com/go/getflash/>Get Flash</a>';
 document.write(alternateContent);
}

$.ajax({
	url: $.appClient.generateUrl({ESStoreroom:'setUserIdFor3DStore'},'x'),
	data: {},
	type: 'POST',
	success: function(msg){
	}
});
</script>