
<style>

.ztree li a span{
	color:#444;
}

</style>
<form id="esfilter">
<table style="width:600px;" id="sift">
	<tr>
		<td>字段名</td>
		<td>比较符</td>
		<td>字段值</td>
		<td>关系符</td>
		<td>增加行</td>
		<td>删除行</td>
	</tr>
	<?php 
	if(isset($condition) && $condition!=""){
		$arrycond= explode('★■◆●',$condition);  
		$size= count($arrycond)>4?count($arrycond):5;
		$lengh=count($arrycond);
		for($i=0;$i<$size;$i++){
			if($i<$lengh){		
				//按第1个、第2个和最后1个逗号分隔 shiyangtao add 20140821
				$cond=$arrycond[$i];
				$condArray=array();
				$separator1 = strpos($arrycond[$i],",");
				$separator3 = strripos($arrycond[$i],",");
				$field = substr($arrycond[$i],0, $separator1);
				$relation = substr($arrycond[$i],$separator3 + 1);
				$tempCond = substr($arrycond[$i],$separator1 + 1, $separator3-$separator1-1);
				$newSeparator2 = strpos($tempCond,",");
				$compare =substr( $tempCond,0, $newSeparator2);
				$text =substr($tempCond,$newSeparator2 + 1);
				$condArray[0] = $field;
				$condArray[1] = $compare;
				$condArray[2] = $text;
				$condArray[3] = $relation;
    ?>    
			<tr>
				<td> <select  name="esfields" style="width: 120px;">
						<option value="">--请选择--</option>
				<?php 
				foreach($searchField as $key=>$val){
					if($condArray[0]==$val->name){
						echo "<option  selected value=".$val->name.">$val->display</option>";
					}else{
						echo "<option  value=".$val->name.">$val->display</option>";
					}	
		        }?>
		             </select></td>
				<td> <select name="comparison"  style="width: 70px;">
						<option  value="equal"  <?php if('equal'==$condArray[1]) echo "selected";?>>等于</option>
						<option value="greaterThan" <?php if('greaterThan'==$condArray[1]) echo "selected";?>>大于</option>
						<option value="lessThan" <?php if('lessThan'==$condArray[1]) echo "selected";?>>小于</option>
						<option value="notEqual" <?php if('notEqual'==$condArray[1]) echo "selected";?>>不等于</option>
						<option value="greaterEqual" <?php if('greaterEqual'==$condArray[1]) echo "selected";?>>大于等于</option>
						<option value="lessEqual" <?php if('lessEqual'==$condArray[1]) echo "selected";?>>小于等于</option>
						<option value="like" <?php if('like'==$condArray[1]) echo "selected";?>>包含</option>
						<option value="notLike" <?php if('notLike'==$condArray[1]) echo "selected";?>>不包含</option>
					</select></td>
				<td><input type="text" value="<?php if(''!=$condArray[2]) echo $condArray[2]?>" name="esfieldvalue" ></td>
				<td><select name="relation"  style="width: 60px;">
						<option value="AND" <?php if('true'==$condArray[3]) echo "selected";?>>并且</option>
						<option value="OR" <?php if('false'==$condArray[3]) echo "selected";?>>或者</option>
						</select></td>
				<td align="center"><a href="javascript:void(0)" class ="esadd"><div class="es_add"></div></a></td>
				<td align="center"><a href="javascript:void(0)" class ="esreduce"><div class="es_del"></div></a></td>
			</tr>
			
		<?php }else{?>
		
			<tr>
				<td> <select name="esfields" style="width: 120px;">
						<option value="">--请选择--</option>
						<option value='name'>名称</option>
						<option value='code'>分类代码</option>
						<option value='period'>保管期限</option>
		             </select></td>
				<td> <select name="comparison"  style="width: 70px;">
						<option value="equal">等于</option>
						<option value="greaterThan">大于</option>
						<option value="lessThan">小于</option>
						<option value="notEqual">不等于</option>
						<option value="greaterEqual">大于等于</option>
						<option value="lessEqual">小于等于</option>
						<option value="like" selected>包含</option>
						<option value="notLike">不包含</option>
					</select></td>
				<td><input type="text" value="" name="esfieldvalue" ></td>
				<td>
					<select name="relation"  style="width: 60px;">
						<option value="AND">并且</option>
						<option value="OR">或者</option>
					</select>
				</td>
				<td align="center"><a href="javascript:void(0)" class ="newfilter"></a></td>
				<td align="center"><a href="javascript:void(0)" class ="delfilter"></a></td>
			</tr>
			
			<?php 
			
				
			}
}
	}else{
	
	      for($i=0;$i<5;$i++){?>
	<tr>
		<td> <select name="esfields" class="filedname" style="width: 120px;">
				<option value="">--请选择--</option>
				<option value='name'>名称</option>
				<option value='code'>分类代码</option>
				<option value='period'>保管期限</option>
             </select></td>
		<td> <select name="comparison" class="comparison" style="width: 70px;">
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select></td>
		<td><input type="text" value="" class="filedvalue" name="esfieldvalue" ></td>
		<td><select name="relation" class="relationship"  style="width: 60px;">
				<option value="AND">并且</option>
				<option value="OR">或者</option>
				</select></td>
		<td><a href="javascript:void(0)" class ="newfilter"></a></td>
		<td><a href="javascript:void(0)" class ="delfilter"></a></td>
	<?php }}?>
		</tr>
</table>
</div>
</form>
<script type="text/javascript">
$(function(){
		//添加行,删除行按钮
		$('.newfilter').die().live('click',function (){
			$($('#sift tr:last').clone()).appendTo($('#sift'));			
		});

		$('.delfilter').die().live('click',function (){
			$('#sift tr').length > 5 ? $(this).closest('tr').remove() : '';
		});
});
</script>

