<div id='filterContents' style='padding:20px;'>
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span>
		<span class='w90 w14090 hei30'>比较符</span>
		<span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">添加行</span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">删除行</span>
	</p>
	<div id='contents'>
		<?php for($fly=1;$fly<6;$fly++){ ?>
		<p class='contbox creatediv'  style="overflow:hidden;">
			<select name="esfields" class='w140 w14090 hei20 filedname'>
				<option value=''>请选择</option>
				<option value='name'>名称</option>
				<option value='code'>分类代码</option>
				<option value='period'>保管期限</option>
				<option value='paperWay'>未来组卷方式</option>
			</select>
			<select name="comparison" class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue'  name="esfieldvalue"  />			
			<select id='' class='w14090 w90 hei20 relationship' name="relation">
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<a class='newfilter'></a><a class='delfilter'></a>
		</p>
		<?php }?>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(".filedname").die().live("change",function(){
		if($(this).val()=="paperWay"){
			$(this).parent("p").find("input[name='esfieldvalue']").hide();
			$(this).closest("p").find("input[name='esfieldvalue']").after('<select name="filedvalue" class="w140 w14090 hei20"><option value="0">---请选择---</option><option value="1">单项工程</option><option value="2">整体项目</option></select>');
			$(this).parent("p").find("select[name='filedvalue']").change(function(){
				$(this).prev().val($(this).val());
			});
		}else{
			$(this).parent("p").find("input[name='esfieldvalue']").show();
			var sel=$(this).parent("p").find("select[name='filedvalue']");
			if(sel!=null){
				sel.remove();
			}
		}
	});
});
</script>