<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/ext/resources/css/ext-all.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESTransferFlow/css/workflow/grapheditor.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESTransferFlow/css/workflow/common.css" />
<link rel='stylesheet' type='text/css' href='<?php echo $tplPath;?>/ESTransferFlow/css/workflow/info_css.css' />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/ext/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/ext/source/locale/ext-lang-zh_CN.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/ext/Utils.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESTransferFlow/js/workflow/GraphEditor.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESTransferFlow/js/workflow/MainPanel.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESTransferFlow/js/workflow/LibraryPanel.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESTransferFlow/js/workflow/mxclient.js"></script>
<div id="createWorkflowDiv" class="createWorkflowArea" 
tplPath="<?php echo $tplPath;?>"  
userName="<?php echo $data[4];?>">
	<div id="wfModel_graph" onClick="hideMwnu()" />
	<div id="wfModel_graph_hidden_form" />
</div>
<script type="text/javascript">
var hideMwnuObject ;
function hideMwnu(){
	if(hideMwnuObject){hideMwnuObject.hide();}
}
function showMsg(msg, type){
	if(type == '1'){
		$.dialog.notice({icon : 'succeed',content : msg,title : '3秒后自动关闭',time : 3});
	} else {
		$.dialog.notice({icon : 'error',content : msg,title : '3秒后自动关闭',time : 3});
	}
}
var setworkfolowModelserachUserkeyword = '';
var setworkfolowModelserachRolekeyword = '';

try{
 	graphWorkflow('<?php echo $data[3];?>');//esGraphXml
 	Ext.getCmp('osWfModel_custom_form_init_hidden_Model_ID').setValue(<?php echo $data[1];?>);//modelId = "-1"
 	Ext.getCmp('osFormBuilder_custom_form_init_hidden_Form_ID').setValue(<?php echo $data[2];?>);//formId
 	Ext.getCmp('osWfModel_custom_form_init_hidden_Model_Type_ID').setValue(<?php echo $data[0];?>);//modelTypeID
}catch(e){
	showMsg('<fmt:message key="os.workflow.graph.exception" />','2');
}
$(function(){
	$(document).keydown(function(event){
		if(event.keyCode == 13) {
			return false;
		}
	});
});
</script>
