<link href="<?php echo $tplPath?>/ESFiling/css/index.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFiling/js/menu.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFiling/js/index.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/js/jquery.input.ztree.js"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>
<script type="text/javascript">
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"文件归档", content:"#esmenu, #esone, #eslist"});
	$(".esleft").css("height",esleftH);//设置左侧菜单
});
</script>
<input type="hidden" id="condition">
<div  class='esmain'>
	<div id="escontent">
			<div id="esmenu" class="esleft">
				<ul id="esStageTree" class="ztree" treenodeid=''></ul>
				<input type="hidden" name="stageCode" id="stageCode" value=""/>
				<input type="hidden" name="stageName" id="stageName" value=""/>
				<input type="hidden" name="stageId" id="stageId" value="" />
			</div>
			<div class="esright" id ="esone">
					<div id="eslist">
					  <table id="esDataList"></table>
			       </div>
			</div>
			<div id="esfileview"></div>
			<div id="esnotfiling"></div>
	</div>
	<div id="transfer"></div>
</div>
<script type="text/javascript">
var winW=$(window).width();
var width='auto';
if($.browser.msie && $.browser.version==='6.0'){
	width=winW-$(".esleft").width()-5;
}
var height='';
var winH=$(window).height();
var eslefttop=$(".esleft").offset().top;
var esleftH=winH-eslefttop-11;
var height=winH-eslefttop-115;
window.onresize=function()
{
	var winW=$(window).width();
	if($.browser.msie && $.browser.version==='6.0'){
		width=winW-$(".esleft").width()-5;
	}
	var winH=$(window).height();
	var height=winH-eslefttop-115;
	$(".flexigrid").css({width:width});	
}
</script>