
<div id='filterContents' style='padding:20px;'>
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span>
		<span class='w90 w14090 hei30'>比较符</span>
		<span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">添加行</span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">删除行</span>
	</p>
	<div id='contents'>
		<?php for($fly=1;$fly<6;$fly++){ ?>
		<p class='contbox creatediv'  style="overflow:hidden;">
			<select name="esfields" class='w140 w14090 hei20 filedname'>
				<option value=''>请选择</option>
				<option value='name'>装置名称</option>
				<option value='firstNo'>主项号</option>
				<option value='secondNo'>子项号</option>
				<option value='deviceNo'>装置单元号</option>
				<option value='baseUnits'>基础设计单位</option>
				<option value='detailUnits'>详细设计单位</option>
				<option value='mainPart'>负责部门</option>
				<option value='supervisionUnits'>监理单位</option>
				<option value='remarks'>备注</option>
			</select>
			<select name="comparison" class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue'  name="esfieldvalue"  />
			<select id='' class='w14090 w90 hei20 relationship' name="relation">
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<a class='newfilter'></a><a class='delfilter'></a>
		</p>
		<?php }?>
	</div>
</div>