<style>
<!--
.button {
	cursor: pointer;
	padding: 5px;
	background-color: #6F6E81;
	color: #FFF;
	border: 0px none;
	outline: 0px none;
}
-->
</style>
<script type="text/javascript"
	src="<?php echo $tplPath;?>/ESDocumentsCollection/js/addOrUpdate.js"></script>
<div class="documentStyle">
	<form id="editDataForm" method="post" enctype="multipart/form-data">
		<input type="hidden" name="id" id="id" value="<?php echo $stagData['id']; ?>" />
		<input type="hidden" name="stageId" id="stageId" value="<?php echo $stageId; ?>" />
		<input type="hidden" name="stageCode" id="stageCode" value="<?php echo $stageCode; ?>" />
		<div class="estransfer">
			<ul>
				<?php  
				$arr = array();//数组存储数据
				$index = 0; //下标
				foreach ( $formData as $value ) {
					
					/** lujixiang 20150403 **/
					if ($value['name']=='stageName' || $value['name']=='deviceName' ||
							$value['name']=='participatoryName' || $value['name']=='documentTypeName' ||
								$value['name']=='engineeringName' || $value['name']=='stageId'){
						continue;
					}
					
					if ($value['name']=='stageCode'){
						echo '<li><span> 选择文件 <font color="red" size="3"> * </font> </span><input type="text" id="stageName" name="stageName" class="selectInput" readonly="readonly" verify="text/200/1/0" value="'.$stagData['stageName'].'"  /><input type="hidden" name="stageCode" id="stageCode" value="'.$stagData['stageCode'].'"/></li>';
					}else if($value['name']=='deviceCode'){
						echo '<li><span> 装置名称 <font color="red" size="3"> * </font> </span><input type="text" id="deviceName" class="selectInput" readonly="readonly" name="deviceName" verify="text/50/1/0" value="'.$stagData['deviceName'].'"  /> <input type="hidden" name="deviceCode" id="deviceCode" value="'.$stagData['deviceCode'].'" /></li>';
					}else if($value['name']=='participatoryCode'){
						echo '<li><span> 拟定部门 <font color="red" size="3"> * </font> </span><input type="text" id="participatoryName" name="participatoryName" verify="text/50/1/0"  class="selectInput" readonly="readonly" value="'.$stagData['participatoryName'].'" /><input type="hidden" name="participatoryCode" id="participatoryCode" value="'.$stagData['participatoryCode'].'" /></li>';
					}else if($value['name']=='documentCode'){
						echo '<li><span> 文件类型代码 <font color="red" size="3"> * </font></span><input type="text" name="documentTypeName" id="documentName" verify="text/50/1/0" value="'.$stagData['documentTypeName'].'" class="selectInput" /><img id="documentBtn" class="clickImg"/><input type="hidden" name="documentCode" id="documentCode" value="'.$stagData['documentCode'].'" /></li>';
					}else if($value['name']=='engineeringCode'){
						echo '<li><span> 文件专业代码 <font color="red" size="3"> * </font> </span><input type="text" name="engineeringName" id="engineeringName" verify="text/50/1/0" value="'.$stagData['engineeringName'].'" class="selectInput" /><img id="engineeringBtn" class="clickImg"/><input type="hidden" name="engineeringCode" id="engineeringCode" value="'.$stagData['engineeringCode'].'" /></li>';
					}else{//过滤出项目代码，调整按部门添加页面字段的顺序
						if($value['name']=='projectCode'){
							echo '<li style="width:260px" ><span>' . $value ['lable'] .'<font color="red" size="3">*</font></span><input type="text" name="' . $value ['name'] . '" id="' . $value ['name'] . '" value="'.$stagData[$value['name']].'" verify="' . $value ['verify'] . '"  isedit="' . $value ['isSystem'] . '" class="notselectInput" /></li>';
						}else{
							$arr[$index] = $value;
							$index++;
						}
					}
				 }
				 foreach ($arr as $value){//遍历
				 	$isNull = '';
				 	$edittage = '';
				 	$liwidth = '260px';
					if ($value ['isNull'] == 1) {
						$isNull = '<font color="red" size="3">*</font>';
					}
				 	if ($value ['type'] == 'BOOL') {
				 		if($stagData[$value['name']] == '否'){
				 			$edittage = '<select name="' . $value ['name'] . '" id="' . $value ['name'] . '"  verify="' . $value ['verify'] . '"  isedit="' . $value ['isSystem'] . '" value="'.$stagData[$value['name']].'" class="notselectInput"><option value="是">是</option><option value="是" selected="'.$stagData[$value['name']].'" >否</option></select>';
				 		}else{
							$edittage = '<select name="' . $value ['name'] . '" id="' . $value ['name'] . '"  verify="' . $value ['verify'] . '"  isedit="' . $value ['isSystem'] . '" value="'.$stagData[$value['name']].'" class="notselectInput"><option value="是" selected="'.$stagData[$value['name']].'" >是</option><option value="否">否</option></select>';
						}
					} else {
						if ($value ['length'] >= 200) {
							$liwidth = '550px';
							$edittage = '<textarea  name="' . $value ['name'] . '" id="' . $value ['name'] . '"  verify="' . $value ['verify'] . '" style="width:440px;margin-bottom:10px;"  isedit="' . $value ['isSystem'] . '" class="notselectInput">'.$stagData[$value['name']].'</textarea>';
						} else {
							$readOnly='';
							if($value['name']=='docNo'){
								$readOnly='readonly';
							}else if($value['name']=='person'){
								$readOnly='readonly';
							}
							$edittage = '<input type="text" name="' . $value ['name'] . '" id="' . $value ['name'] . '" value="'.$stagData[$value['name']].'" verify="' . $value ['verify'] . '"  isedit="' . $value ['isSystem'] . '"  '.$readOnly.' class="notselectInput" />';
						}
					}
					echo '<li style="width:' . $liwidth . '" ><span>' . $value ['lable'] . $isNull . '</span>' . $edittage . '</li>';
				}	
				?>
			</ul>
		</div>
	</form>
	<div class="esbottom">
		<table id="efiletable" style="width: auto;">
		</table>
	</div>
</div>