<style>
	.myFormModelShowPkg{width:auto;height:300px;overflow-y:auto;overflow-x:hidden;position:relative;top:0px;}
	.myFormModelShowPkg2{width:auto;height:500px;overflow-y:auto;overflow-x:hidden;position:relative;top:0px;}
	.myFormModelShowPkgChild{width:780px;height:20px;position:relative;}
	.myFormModelShowPkgChild2{hide:true;}
	.myFormModelShowPkg2 table {border-collapse: separate;border-spacing: 1px;border-color: gray;} 
</style>
<div>
	<div id="myFormModelShowPkgDIV" class="myFormModelShowPkg">
			<?php echo $data[0]; ?>
	</div><br/>
	<div id="myFormModelShowPkgChildDIV" class="myFormModelShowPkgChild">
		<table id='myFormModelShowPkgChildTABLE'></table>
	</div>
</div>
