<link href="<?php echo $tplPath?>/ESFullTextSearch/css/index.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>

<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>3));?>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>

<div class='paper' id='ESPaper'>
	 <div class="leftnav"><ul>
		</div>
	<div class='so-paper'>
		<div class='so-so' id='soso'>
			<div class='base-so'>
				<div class='so'>
					<input type='text' id='searchWord' value='' placeholder='多个关键字用空格分开'/>
					<a id="NY_searchall" href='javascript:;' class='searchall'>搜索</a>
				</div>
				<div class='adv-so-bn'>
					<a href="<?php echo $esaction->generateUrl(array('ESFullTextSearch'=>'intricate'));?>">高级搜索</a>
				</div>
			</div>
		</div>
		<div class='so-result' id='so_result'></div>
	</div>
	<div class='so-hd'>
		<div class='so-car' id='car'>
			<i>提交申请</i>
			<span class='so-st'><?php echo count($SESScommon);?></span>
			<div class='product-list' id='product_list'>
				<?php
				if(count($SESScommon)==0){
					echo "<h2 class='pl-null'>没有申请数据！</h2>";//liqiubo 20141011修改显示的文字，修复bug 1270
				}else{
					$shop="<h2 class='pl-hd'><b>申请数据清单</b></h2>";//liqiubo 20140929 修改显示的文字，修复bug 1270
					$shop.="<ul class='pl-ul'>";
					
					foreach($SESScommon as $v){
						$shop.="<li id='".$v->id."' class='thisli_".$v->id."'>";
						$shop.="<span></span>";
						$shop.="<div class='titlestyle'>".$v->title."</div>";
						$shop.="<div class='deletestyle'><a href='javascript:delFormArchivesCar(".$v->id.");'>删除</a></div>";
						$shop.="</li>"; 
					}
					$shop.="</ul>";
					$shop.="<div class='pl-hr'><a onclick='javascript:delFormArchivesCar();'>清空</a></div>";
					$shop.="<div class='pl-sb'>";
					$shop.="<a href='javascript:submitBespeakCar();'>提交预约</a>";
					$shop.="</div>";
					echo $shop;
				}
				?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFullTextSearch/js/index.js"></script>
<script type="text/javascript">
window.onload = function (){ 
	setEstW();
};

//窗口大小变动事件
$(window).resize(function() {
	setEstW();
});

function setEstW(){
	//nav标头宽度自动调整
	var estW=$("#ESPaper").css("width").split("px")[0]-230;
	$("#estabs").css("padding-left",estW/2-54).css("width",estW/2+54);
	$(".seporateLine").css("width",estW);
	$(".seporateArea").css("width",estW);

	var height = $(window).height()-110;	// 可见总高度 - 176为平台头部高度
	if(navigator.userAgent.indexOf("MSIE 8.0")>0){
		height = height-4;
	}
	$("#ESPaper").css({height:height});
}
</script>