<link href="<?php echo $tplPath?>/ESFullTextSearch/css/index.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFullTextSearch/js/index.js"></script>
<link rel="stylesheet" href="<?php echo $tplPath;?>/public/SWFUpload/css/swfupload.css" type="text/css"/>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/swfupload.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/swfupload.queue.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/fileprogress.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/handlers.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/DatePicker/WdatePicker.js"></script>
<link href="<?php echo $tplPath;?>/public/DatePicker/skin/WdatePicker.css" rel="stylesheet" type="text/css">
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>3));?>
<input type="hidden" id ="tplPath" value="<?php echo $tplPath;?>" />
<div class="main">
<div class="search">
<div class="remind"></div>
<div class="disp">
<form name="myform" onsubmit="return false;">
	<div class='searchBox2'>
		<span class='leftbg2'></span>
		<div class='middlebg2'>
			<input id="onword" type='text' class='searchText2' maxlength="100" name="key" placeholder='多个关键字用空格分开' value="" style="line-height: 30px;" />
			<!-- <input type='button' class='searchSubmit2' value='搜索' /> -->
		</div>
		<span class='rightbg2'></span>
		<input type='button' class='searchSubmit2' value='搜索' />
	</div>
	<a class="advSearchTitle" href="<?php echo $esaction->generateUrl(array('ESFullTextSearch'=>'intricate'));?>">高级搜索</a>
</form>
</div>
<div class="clear"></div>
</div>
</div>

<script type="text/javascript">
$.fn.placeholder = function(){
	var searchText = this;
	var searchValue = searchText.attr('placeholder');
	if( searchText.length > 0 ){
		if ( !( 'placeholder' in document.createElement('input') ) ){
			searchText.css('color','#A9A9A9').val(searchValue).bind('focus',function(){
				searchText.css('color','#000000');
				if ( this.value==searchValue) {this.value=''; };
			}).bind('blur',function(){
				if ( $.trim(this.value)=='' ){searchText.css('color','#A9A9A9'); this.value=searchValue; };
			});
		}
	}
}
$(function(){
	/** 隐藏nav导航条 **/
	$("#estabs,.seporateArea,.seporateLine").css("display","none");
	$('#onword').placeholder();
});
</script>