<link href="<?php echo $tplPath?>/ESDocumentType/css/index.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESDocumentType/js/index.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESDocumentType/js/menu.js"></script>

<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>
<script type="text/javascript">
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"文件类型代码", content:"#esmenu,#esone,#eslist"});
	$(".esleft").css("height",esleftH);//设置左侧菜单
});
</script>
<div  class='esmain'>
	<div id="escontent">
			<div id="esmenu" class="esleft">
				<ul id="esStageTree" class="ztree"></ul>
				<input type="hidden" id="selTreeId" name="selTreeId" value="0"/>
				<input type="hidden" id="treecode" value=''>
			    <input type="hidden" id="treename" value=''>
			</div>
			<div class="esright" id ="esone">
					<div id="eslist">
					  <table id="esStageList"></table>
			       </div>
			</div>
			<div id="esfileview"></div>
			<div id="esnotfiling"></div>
	</div>
	<div id="transfer"></div>
</div>
<script type="text/javascript">
var winW=$(window).width();
var width='auto';
if($.browser.msie && $.browser.version==='6.0'){
	width=winW-$(".esleft").width()-5;
}
var height='';
var winH=$(window).height();
var eslefttop=$(".esleft").offset().top;
var esleftH=winH-eslefttop-11;
var height=winH-eslefttop-115;
window.onresize=function()
{
	winW=$(window).width();
	if($.browser.msie && $.browser.version==='6.0'){
		width=winW-$(".esleft").width()-5;
	}
	winH=$(window).height();
	height=winH-eslefttop-115;
	esleftH=winH-eslefttop-11;
	$(".esleft").css("height",esleftH);
	$(".flexigrid").css({width:width});	
}
</script>