<style type="text/css">
#editReport table tr {
	height: 50px;
}

span.editReportType input {
	float: left;
	margin-left: 25px;
}

span.editReportType label {
	float: left;
	margin-right: 45px;
}
</style>
<div style="height: 300px;">
	<!--
<div style="margin-top: 10px;font-size:24px;font-weight:bold;border-bottom:1px solid #CCC;">条目概览</div>
-->
	<div style="padding-top: 10px;">
		<form id="editReport" method="post" enctype="multipart/form-data">
			<table style="height: 100px;">
				<tr>
					<td>报表标题:</td>
					<td><input type="text" name="title" verify="unspecial/100/1/0"
						id="title" value="<?php echo $report->title;?>"
						style="width: 380px; height: 20px;" />
						<input type="hidden" name="oldTitle" verify="unspecial/100/1/0"
						id="oldTitle" value="<?php echo $report->title;?>"/>
					</td>
				</tr>
				<tr>
					<td>报表类型:</td>
					<td><select name="mytype" disabled="true"
						style="width: 380px; height: 20px;">
							<option value="<?php echo $report->reportType;?>">
	    	<?php
						
						if ($report->reportType == "collection") {
							echo '文件收集';
						} elseif ($report->reportType == "using") { 
							echo '文件借阅';
						} elseif ($report->reportType == "workflow") {
							echo '工作流';
						}else {
							echo '';
						}
						?>
	    </option>
					</select></td>
				</tr>
				<tr>
					<td>输出格式:</td>
					<td><span class="editReportType"><input id="s1" class="radio"
							type="radio" name="resourceleve"
							<?php if ($report->reportstyle=="pdf") echo 'checked="checked"';?>
							value="pdf"><label for="s1">PDF格式</label></span> <span
						class="editReportType"><input id="s2" class="radio" type="radio"
							name="resourceleve"
							<?php if ($report->reportstyle=="rtf") echo 'checked="checked"';?>
							value="rtf"><label for="s2">WORD格式</label></span> <span
						class="editReportType"><input id="s3" class="radio" type="radio"
							name="resourceleve"
							<?php if ($report->reportstyle=="xls") echo 'checked="checked"';?>
							value="xls"><label for="s3">EXCEL格式</label></span></td>
				</tr>
				<tr id="myproces">
					<td>模版文件:</td>
					<td><input id="btnAdd" type="button" value=" 添加文件 " /> <input
						id="btnCancel" style="display: none;" type="button" value=" 取消" /></td>
				</tr>
				<tr>
					<td></td>
					<td><div style="height: 25px; width: 30px;" id="fsUploadProgress"></div></td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	// 上传电子文件		
		var upload = new SWFUpload({
			//提交路径
			upload_url: "<?php echo $ip;?>/addReport",
			//向后台传递额外的参数
			//上传文件的名称
			file_post_name: "file",			
			file_size_limit : "102400",	// 100MB
			file_types : "*.jrxml",
			file_types_description : "jrxml文件",
			file_upload_limit : "1",
			file_queue_limit : "0",

			// 事件处理
			swfupload_loaded_handler : swfuploadLoaded,
			file_dialog_start_handler : fileDialogStart,
			file_queued_handler : fileQueued,
			file_queue_error_handler : fileQueueError,
			file_dialog_complete_handler : fileDialogComplete,
			upload_start_handler : uploadStart,
			upload_progress_handler : uploadProgress,
			upload_error_handler : uploadError,
			upload_success_handler : uploadSuccess,
			upload_complete_handler : uploadComplete,

			// 按钮的处理
			button_image_url : "<?php echo $tplPath?>/public/SWFUpload/img/ButtonUpload72.png",
			button_placeholder_id : "btnAdd",
			button_width: 72,
			button_height: 28,			
			// Flash文件地址设置
			flash_url : "<?php echo $tplPath?>/public/SWFUpload/js/swfupload.swf",			
			custom_settings : {
				progressTarget : "fsUploadProgress",
				cancelButtonId : "btnCancel",
				startButtonId : "btnStarts",
				startButtonFlag : "editReport",
				// 上传成功的回调函数
				//uploadSuccess : function(file, data){$("#report").flexOptions().flexReload();}
			},
			debug: false
		});
		$("#btnCancel").click(function(){cancelQueue(upload);});
		$("#btnStarts").click(function(){
			var form=$('#editReport');
    		if (!form.validate()) {
    			return false;
    		}
			var title = $("#editReport input[name='title']").val();
			var resourceleve = $("#editReport .radio:checked").val();
			var rtitle = $.trim(title);
			$.ajax({
				type: "POST",
    	    	url:$.appClient.generateUrl({ESReport:'checkTitleUnique'},'x'),
    	    	data:{title:rtitle},
    	    	success:function(data){
        	    	if(data == 'true' || '<?php echo $report->title;?>'==rtitle){
            	    	var fileFlag = false;
						var status = $(".progressBarStatus");
						$.each(status,function(){
							if('等待上传...' == $(this).html()){
								fileFlag = true;
							}	
						});
						if(!fileFlag){//如果不存在文件
							$.ajax({
								type: "POST",
				    	    	url:$.appClient.generateUrl({ESReport:'saveReportTemForEdit'},'x'),
								data:{title:rtitle,reportid:"<?php echo $report->idReport;?>",reportstyle:resourceleve,reportType:"<?php echo $report->reportType;?>"},
				    	    	success:function(result){
					    	    	if(result == 'true'){
					    	    		$.dialog.notice({icon:'succeed', content:"保存成功", time:3});
					    	    		$("#report").flexOptions().flexReload();
					    	    		art.dialog.list['editReportPanel'].close();
					    	    	}else{
					    	    		$.dialog.notice({icon:'error', content:"保存失败", time:3});
						    	    }	
				    	    	},
				    		    cache:false
							});
						}else{
	        				upload.addPostParam("reportid","<?php echo $report->idReport;?>");
	        				upload.addPostParam("reportname",rtitle);
	        				upload.addPostParam("reportstyle",resourceleve);
	        				upload.addPostParam("uploader","<?php echo $report->uplodaer;?>");
	        				upload.addPostParam("reportType","<?php echo $report->reportType;?>");
	        				startQueue(upload);
						}	
        	    	}else{
        	    		$.dialog.notice({icon:'warning', content:"标题为【"+rtitle+"】的报表已经存在，请重新填写报表标题!", time:3});
        				return;
                	}	
    	    	},
    		    cache:false
    		});			
		});
});

//上传成功的回调函数
function uploadSuccess(file,data){
	if(!this.getStats().upload_errors) {
		this.destroy();//当不需要再使用SWFUpload了的时候,可以使用该方法来销毁它的实例和dom元素
		dia2.close();//关闭添加窗口
		$("#report").flexOptions().flexReload();
	}
}
</script>