<div
	style="float: left; width: 400px; height: 100px; line-height: 100px;"
	id="statisticsTypeDiv">
	<div style="float: left; width: 40%; height: 100%; text-align: right;">统计方案类型：&nbsp;&nbsp;&nbsp;</div>
	<div style="float: left; width: 60%; height: 100%; text-align: left;">
		<input type="radio" name="statisticsType" id="type0" value="0"
			checked="checked" /><label style="display: inline;" for="type0">数据节点统计</label>
		<input type="radio" name="statisticsType" id="type1" value="1" /><label
			style="display: inline;" for="type1">分组统计</label>
	</div>
</div>