<script type="text/javascript" src="<?php echo $tplPath;?>/ESCatalogCheck/js/filter.js"></script>
<div style='overflow-y: auto; overflow-x: hidden; position: relative;'>
	<div style="padding-top: 30px;">
			<table id="table_detail" style="height: 100px;">
				<tr>
					<td>装置：</td>
					<td>
					<input type="text" name="device"  id="device" class="selectInput"  readonly="readonly" value="" />
					<input type="hidden" name="deviceNo"  id="deviceNo"  value="" />
					</td>
				</tr>
			</table>
	</div>
</div>
