<!-- xiewenda -->
<form id="editStandardDocument" action=""	method="post">
<div class="estransfer">
<ul>
<input type="hidden" name="id" value="<?php echo $id;?>" />
<li><span>编号<font color="red" size="3">*</font></span><input  type="text" name="no"  verify="desc/20/1/0"  value="<?php echo $no;?>"><input type="hidden" name="oldNo" id="oldNo" value="<?php echo isset($no)?$no:''; ?>"/></li>
<li><span>中文名称<font color="red" size="3">*</font></span><input type="text" name="chineseName"   verify="china/100/1/0"   value="<?php echo $chineseName;?>"></li>
<li style="width:600px"><span>文件描述</span><textarea  name="description"   verify="text/100/0/0" style="width:445px;height:50px;float:left"><?php echo $description;?></textarea></li>
<li style="width:600px"><span>所属规定<font color="red" size="3">*</font></span><input type="text" style="width:445px" name="regulation_name" title="提示：单击弹出规定列表" verify="text/100/1/0" readonly="readonly"  value="<?php echo $regulation_name;?>">
<input type="hidden" name="regulation_id" value="<?php echo $regulation_id;?>" />
</li>
<li><span>附件<font color="red" size="3">*</font></span><input type="button" id="fileUp" value='附件上传' class='fileUpButton' style="height:25px"/>
<input type="hidden" name="filePath" value="<?php echo $filePath;?>"/>
<input type="hidden" name="fileName" value="<?php echo $fileName;?>"/>	
</li>
</ul>
</div>
<div id="loadfile" style="margin-left:150px"></div>
</form>
 <script type="text/javascript">
 $(function(){
	 var  fileName='<?php echo $fileName;?>';
	 var  filePath='<?php echo $filePath;?>';
	 if(fileName){
		 $('#loadfile').append('<div><a href="javascript:void(0)" title="点击下载附件">'+fileName+'</a><input type="hidden" name="filePath" value="'+filePath+'"/><input type="hidden" name="fileName" value="'+fileName+'"/></div>');
		 var NY_img = '<img style="cursor:pointer;" id="NI_img"  src="<?php echo $tplPath;?>/public/flexigrid/css/images/cross.png" alt="删除附件" title="删除附件" />';
	 $('#loadfile div').hover(
	 		function() {
	 			$('#NI_img').remove();
	 			$(this).find('a').after(NY_img);
	 		} ,
	 		function() {
	 			$('#NI_img').remove();
	 		}
	 	);
	 }
 });
 </script>
 