<style>
<!--
.button {cursor: pointer;padding: 5px;background-color: #6F6E81;color: #FFF;border: 0px none;outline: 0px none;}
-->
</style>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESContractItem/js/addOrUpdate.js"></script>
<div style="">
	<div style="padding-top: 30px;">
		<form id="editContractItemForm" method="post" enctype="multipart/form-data">
		    <input type="hidden" name="id" id="id" value="<?php echo isset($id)?$id:''; ?>"/>
			<table id="table_detail" style="height: 400px;">
				<tr>
					<td>合同工程名称：</td>
					<td><input type="text" name="escontractname" id="escontractname" value="<?php echo isset($escontractname)?$escontractname:''; ?>" style="width: 380px; height: 20px;" verify="unspecial/64/1/0" /></td>
				</tr>
				<tr>
					<td>合同号：</td>
					<td><input type="text" name="escontractnum" id="escontractnum" value="<?php echo isset($escontractnum)?$escontractnum:''; ?>" style="width: 380px; height: 20px;" verify="english-num/20/1/0" />
					<input type="hidden" name="oldEscontractnum" id="oldEscontractnum" value="<?php echo isset($escontractnum)?$escontractnum:''; ?>"/></td>
				</tr>
				<tr>
					<td>项目名称：</td>
					<td><input type="text" name="esprojectname" id="esprojectname" value="<?php echo isset($esprojectname)?$esprojectname:''; ?>" style="width: 380px; height: 20px;" verify="unspecial/64/0/0" /></td>
				</tr>
				<tr>
					<td>负责装置：</td>
					<td><input type="text" name="esdevice" id="esdevice"
						class="selectInput" readonly="readonly" value="<?php echo isset($esdevice)?$esdevice:''; ?>"
						style="width: 380px; height: 20px;" verify="text/64/1/0" />
						<input type="hidden" name="esdeviceNo"  id="esdeviceNo"  value="" />
						<input type="hidden" id="esdeviceId" value="0" /></td>
				</tr>
				<tr>
					<td>中标单位：</td>
					<td><input type="text" name="escompany" id="escompany"
						class="selectInput" readonly="readonly" value="<?php echo isset($escompany)?$escompany:''; ?>"
						style="width: 380px; height: 20px;" verify="text/64/1/0" />
						</td>
				</tr>
				<tr>
					<td>联系人：</td>
					<td><input type="text" name="esperson" id="esperson" value="<?php echo isset($esperson)?$esperson:''; ?>" style="width: 384px; height: 25px;" verify="unspecial/20/0/0" /></td>
				</tr>
				<tr>
					<td>联系方式：</td>
					<td><input type="text" name="esperstel" id="esperstel" value="<?php echo isset($esperstel)?$esperstel:''; ?>" style="width: 384px; height: 25px;" verify="mobile" /></td>
				</tr>
			</table>
		</form>
	</div>
</div>