<div class='public_filter'>
	<div class='propmt_fields'>
		<span class='long_fields_tag'>字段名</span>
		<span class='short_fields_tag'>比较符</span>
		<span class='long_fields_tag'>字段值</span>
		<span class='short_fields_tag'>关系符</span>
		<span class='add_del_tag'>添加行</span>
		<span class='add_del_tag'>删除行</span>
	</div>
	
	<div class='filter_conditions' id='filter_conditions'>
	<?php
		for($tagNumber=1; $tagNumber<6; $tagNumber++){
	?>
		<div class='filter_condition'>
			<div class='long_fields_tag'>
				<select class='long_area CHANGE_EVENT filter_Field'>
					<option value='empty'>请选择</option>
					<?php
						foreach ($options as $key => $value)
						{
							echo '<option value="'. $key .'">'. $value .'</option>';
						}
					?>
				</select>
			</div>
			<div class='short_fields_tag'>
				<select class='short_area filter_Comparison'>
					<option value="equal">等于</option>
					<option value="greaterThan">大于</option>
					<option value="lessThan">小于</option>
					<option value="notEqual">不等于</option>
					<option value="greaterEqual">大于等于</option>
					<option value="lessEqual">小于等于</option>
					<option value="like" selected>包含</option>
					<option value="notLike">不包含</option>
				</select>
			</div>
			<div class='long_fields_tag FILTER_VALUE position'>
				<input type='text' class='filter_Value long_area ext_long_area' />
			</div>
			<div class='short_fields_tag'>
				<select class='short_area filter_Relation '>
					<option value="and">并且</option>
					<option value="or">或者</option>
				</select>
			</div>
			<a class='new_filter_condition'></a>
			<a class='del_filter_condition'></a>
		</div>
	<?php }?>
	</div>
</div>
<script type='text/javascript'>
var _widget = {
		change : function (that){
					var html = null;
					if(that.value == 'status'){
						htm = '<select class="filter_Value long_area"><option value="0">未发布</option><option value="1">已发布</option></select>';
					}else if(that.value == 'authorId'){
						htm = "<input type='text' class='filter_Value long_area ext_long_area' />";
						//htm = '<input type="text" class="filter_Value long_area ext_long_area" id="select_user_btn" />';
					}else if(that.value == 'createTime'){
						htm = "<input type='text' class='filter_Value long_area ext_long_area wdate' value='<?php echo date("Y-m-d")?>' />";
					}else{
						htm = "<input type='text' class='filter_Value long_area ext_long_area' />";
					}

					$(that).parent().parent().find('.FILTER_VALUE').html(htm);
				}
};

var _user = {
		tmpObj: null,
		setting: {
			view: {
				dblClickExpand: true,
				showLine: false
			},
			data: {
				simpleData: {
					enable: true
				}
			},
			async: {
				enable:true,
				type:'get',
				url:$.appClient.generateUrl({ESIdentify:'GetOrgList'},'x'),
				autoParam:["id=oid"]
			},
			callback: {
				onClick: function (event, nodeId, treeNode){
					
					var url = $.appClient.generateUrl({ESArchiveDestroy:'FindUserListByOrgid',oid:treeNode.id},'x');
					$("#user_list").flexOptions({url:url}).flexReload();
				}
			}
		},
		init : function (){
			var that = this;
			$.getJSON(
				$.appClient.generateUrl({ESIdentify:'GetOrg'},'x'),
				function (nodes){
					var html = ['<div style="width:700px; height:400px; float:left;"><div style="width:230px; height:390px; float:left; overflow:scroll;" class="ztree" id="org_tree"></div>'];
					html.push('<div style="width:460px; height:400px; float:left;"><table id="user_list"></table></div></div>');
					
					//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
					$.dialog({
						id:'_select_user_',
						title:'选择人员',
						content:html.join(''),
						padding:'0',
						width:700,
						height:400,
						cancelVal:'关闭',
						cancel:true
					});
					//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$//
					
					$.fn.zTree.init($('#org_tree'),that.setting,nodes);
					
					// 用户列表
					$("#user_list").flexigrid({
						url:false,
						dataType: 'json',
						colModel : [
							{display: '序号', name : 'linenumber', width : 40, align: 'center'}, 
							{display: '选择', name : 'radio', width : 40, align: 'center'},
							{display: '姓名', name : 'userName', width : 80, align: 'center'},
							{display: '部门', name : 'orgName', width : 280, align: 'center'},
							{display: '职务', name : 'deptPost', width : 280, align: 'center'},
							{display: '联系方式', name : 'mobTel', width : 280,align: 'center'}
						],
						usepager: true,
						nomsg: '没有数据',
						useRp:true,
						width:460,
						height:340
					});
				},
				'json'
			);
			
		},
		select : function (that){
			var tmpObj = this.tmpObj;
			var info = that.val().split('@'); // qimq@齐鸣秋@中国联通总部管理部门@总经理@@001000
			var uid = info[0]; // 英文名
			var une = info[1]; // 中文名
			tmpObj.val(une);
			tmpObj.attr('name',uid);
			$.dialog.list._select_user_.close();
		}
};

$('.CHANGE_EVENT').die().live('change',function (){
	_widget.change(this); // 当前下拉框值和要替换的DIV内容
});

$('.wdate').live('click', function (){
	WdatePicker({dateFmt:'yyyy-MM-dd'});
});

//添加行,删除行按钮
$('.new_filter_condition').die().live('click',function (){
	$($('#filter_conditions>div:last').clone()).appendTo($('#filter_conditions'));
});

$('.del_filter_condition').die().live('click',function (){
	$('#filter_conditions>div').length > 1 ? $('#filter_conditions>div:last').remove() : '';
});

$('#select_user_btn').die().live('click',function (){
	_user.tmpObj = $(this).parent().find('input');
	_user.init();
});

$('#user_list tr').die().live('dblclick',function (){
	_user.select($(this).find('input'));
	
});

$('#user_list input').die().live('click',function (){
	_user.select($(this));
});
</script>