<style>
<!--
.button {cursor: pointer;padding: 5px;background-color: #6F6E81;color: #FFF;border: 0px none;outline: 0px none;}
-->
</style>
<div style="">
	<div style="padding-top: 30px;">
		<form id="addParticipatoryForm" method="post" enctype="multipart/form-data">
			<table id="table_detail">
				<tr style="height: 50px;">
					<td>名称<font color="red" size="3">*</font></td>
					<td><input type="text" name="name" id="name" verify="text/50/1/0" value=""
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr style="height: 50px;">
					<td>代码<font color="red" size="3">*</font></td>
					<td><input type="text" name="code" id="code" verify="china-english-num/50/1/0" value=""
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr style="height: 50px;">
					<td>类型<font color="red" size="3">*</font></td>
					<td><input type="radio" name="partType" id="partTypeUnits1" checked="checked" value="1"/><label style="display: inline;" for="partTypeUnits1">业主单位</label>
					<input type="radio" name="partType" id="partTypeUnits2" value="2"/><label style="display: inline;" for="partTypeUnits2">设计单位</label>
					<input type="radio" name="partType" id="partTypeUnits3" value="3"/><label style="display: inline;" for="partTypeUnits3">施工单位</label>
					<input type="radio" name="partType" id="partTypeUnits4" value="4"/><label style="display: inline;" for="partTypeUnits4">监理单位</label>
					<input type="radio" name="partType" id="partTypePart" value="5"/><label style="display: inline;" for="partTypePart">部门</label>
					</td>
				</tr>
				<tr style="height: 50px;line-height: 50px;">
					<td valign="top">文控人员<font color="red" size="3">*</font>&nbsp;&nbsp;</td>
					<td><span class="button findControler" style="padding-right:22px; background:#6F6E81 url(<?php echo $tplPath?>/public/flexigrid/css/images/add.png) no-repeat right;">文控人员</span>
					</td>
				</tr>
				<input type="hidden" name="tplPath" id="tplPath" value="<?php echo $tplPath ?>" />
			</table>
		</form>
	</div>
</div>