<form id="addMemberForm">
	<div style="width: 500px; height: 150px; margin: 20px 5px 10px 5px;">
		<div style="float: left; width: 490px; height: 33%;">
			<div
				style="float: left; width: 40%; height: 100%; text-align: center;">部门&nbsp;&nbsp;</div>
			<div style="float: left; width: 60%; height: 100%;">
				<input type="text" id="partName" name="partName" readonly="readonly"
					value="<?php echo $partName; ?>" style="width: 200px;" /> <input
					type="hidden" id="partId" name="partId"
					value="<?php echo $partId; ?>" />
			</div>
		</div>
		<div style="float: left; width: 490px; height: 33%;">
			<div
				style="float: left; width: 40%; height: 100%; text-align: center;">
				员工<font color="red" size="3">*</font>
			</div>
			<div style="float: left; width: 60%; height: 100%;">
				<input type="text" id="userName" name="userName" readonly="readonly"
					value="" verify="text/100/1/0" style="width: 200px;" /><span
					style="margin: 9px 0px 0px -20px; border: 0px; cursor: pointer;"><img
					title="单击我,选择部门员工"
					src="<?php echo $tplPath;?>/ESParticipatory/images/group.png" /></span>
				<input type="hidden" id="userId" name="userId" value="" />
			</div>
		</div>
		<div style="float: left; width: 490px; height: 33%;">
			<div
				style="float: left; width: 40%; height: 100%; text-align: center;">
				职位<font color="red" size="3">*</font>
			</div>
			<div style="float: left; width: 60%; height: 100%;">
				<input type="radio" name="officeType" id="officeType1"
					checked="checked" value="1" /><label style="display: inline;"
					for="officeType1">领导</label> <input type="radio" name="officeType"
					id="officeType2" value="2" /><label style="display: inline;"
					for="officeType2">高级工程师</label> <input type="radio" name="officeType"
					id="officeType3" value="3" /><label style="display: inline;"
					for="officeType3">文控人员</label><input type="radio" name="officeType"
					id="officeType4" value="4" /><label style="display: inline;"
					for="officeType4">普通员工</label>
			</div>
		</div>
	</div>
</form>