<script type="text/javascript" src="<?php echo $tplPath;?>/ESCollaborative/js/filter.js"></script>
<div style='overflow-y: auto; overflow-x: hidden; position: relative;'>
	<div style="padding-top: 25px;">
			<table id="table_detail" style="height: 100px;">
				<tr>
					<td>选择收集范围：</td>
					<td>
					<input type="text" name="stageName"  id="stageName" class="selectInput"  readonly="readonly" value="" />
					<input type="hidden" name="stageId"  id="stageId"  value="" />
					</td>
				</tr>
			</table>
	</div>
</div>
