<table id="borrowlist"></table>
<script type="text/javascript">
	$("#borrowlist").flexigrid({
		url:$.appClient.generateUrl({ESDocumentBorrowing:'getJson',type:'<?php echo $type;?>',id:'<?php echo $id;?>'}),
		dataType: 'json',
		colModel : [
			{display: '序号', name : 'num', width : 20, align: 'center'},
			{display: '<input type="checkbox" name="path" onclick=selectAll(checked,"#borrowlist")>', name : 'ids', width : 40, align: 'center',metadata:'ids'},
			{display: '项目名称', name : 'itemName', width : 120, align: 'left',metadata:'itemName'},
			{display: '收集范围代码', hide:true, name : 'stageCode', width : 40, align: 'left',metadata:'stageCode'},
			{display: '收集范围名称', name : 'stageName', width : 100, align: 'left',metadata:'stageName'},
			{display: '装置分类代码', hide:true, name : 'deviceCode', width : 40, align: 'left',metadata:'deviceCode'},
			{display: '装置分类名称', name : 'deviceName', width : 100, align: 'left',metadata:'deviceName'},
			{display: '拟定部门代码', hide:true, name : 'participatoryCode', width : 40, align: 'left',metadata:'participatoryCode'},
			{display: '拟定部门名称', name : 'participatoryName', width : 100, align: 'left',metadata:'participatoryName'},
			{display: '文件类型代码', hide:true, name : 'documentCode', width : 50, align: 'left',metadata:'documentCode'},
			{display: '文件类型名称', name : 'documentTypeName', width : 100, align: 'left',metadata:'documentTypeName'},
			{display: '文件专业代码', hide:true, name : 'engineeringCode', width : 50, align: 'left',metadata:'engineeringCode'},
			{display: '文件专业名称', name : 'engineeringName', width : 100, align: 'left',metadata:'engineeringName'},
			{display: '文件标题', name : 'title', width : 80, align: 'left',metadata:'title'},
			{display: '文件编码', name : 'docNo', width : 50, align: 'left',metadata:'docNo'},
			{display: '拟定人', name : 'person', width : 50, align: 'left',metadata:'person'},
			{display: '日期', name : 'date', width : 80, align: 'center',metadata:'date'},
			{display: '附件', name : 'Attachments', width : 40, align: 'right',metadata:'Attachments'}
		],
		buttons:[],
		usepager: true,
		useRp: true,
		rp: 20,
		nomsg:"没有数据",
		showTableToggleBtn: false,
		pagetext: '第',
		outof: '页 /共',
		width: 596,
		height: 271,
		pagestat:' 显示 {from} 到 {to}条 / 共{total} 条'
	});
	function queryDataList(){
		var keyWord = $("#queryDataList").val();
		if(keyWord=='请输入关键字'){
			keyWord='';
		}
		var url = $.appClient.generateUrl({ESDocumentBorrowing:'getJson',type:'<?php echo $type;?>',id:'<?php echo $id;?>',keyWord: encodeURI(keyWord)},'x');
		$("#borrowlist").flexOptions({url: url,newp: 1}).flexReload();
	}
	$('#borrowlistbox div[class="tDiv2"]').prepend('<span style="float:left;margin:2px 0px 3px 5px ;padding-right:3px;">列表数据</span>').append('<div class="find-dialog"><input id="queryDataList" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="keyWord" value="请输入关键字" /><span onclick="queryDataList()"></span></div>');
	$('#borrowlistbox div[class="tDiv"]').css("border-top","1px solid #ccc");

	$(document).keydown(function(event) {
	    if (event.keyCode == 13 && document.activeElement.id == 'queryDataList') {
	    	queryDataList();
	    }
	});
	//全选
	function selectAll(status,obj){
		$(obj).find("input[type='checkbox']").attr('checked',status);
		if(status){
			$(obj).find("tr").addClass("trSelected");
		}else{
			$(obj).find("tr").removeClass("trSelected");
		}
	}
	
	//筛选增加、减少行 
	$(function(){
		var i=0;
		$('.esadd').die().live('click',function(){
			var $lastTr=$('#sift tr:last')
			$lastTr.clone().insertAfter($lastTr);
			i++;
		});
		$(".esreduce").die().live('click',function(){
			if($('#sift tr').length == 2 )
			{
				return false;
			}else{
				$(this).parent().parent().remove();
				i--;
			}
		});
	});
	//获取筛选条件
	function filterValue()
	{
		var $where='';
		$("#sift tr:gt(0)").each(function(i){
			 var esfields=$("[name='esfields']").eq(i).val();
			 var comparison=$("[name='comparison']").eq(i).val();
			 var esfieldvalue=$("[name='esfieldvalue']").eq(i).val();
			 var relation=$("[name='relation']").eq(i).val();
			 if(esfieldvalue){
				 if(relation=="AND"){
					 relation='true';
				 }else{
					 relation='false';
				 }
				 $where+=esfields+','+comparison +','+esfieldvalue+','+relation+'@';
			 }
		});
		return $where;
	}
	//筛选档案著录明细
	function filterList(){
		$.ajax({
		    url:$.appClient.generateUrl({ESIdentify:'filter',status:4,strucid:strucid},'x'),
		    success:function(data){
		    	$.dialog({
			    	title:'筛选数据',
		    		width: '50%',
		    	    height: '40%',
		    	   	fixed:true,
		    	    resize: false,
			    	content:data,
			    	okVal:'确定',
				    ok:function(){
						var thisDialog=this;
						var condition=filterValue();
						thisDialog.close();
						$("#borrowlist").flexOptions({newp:1,query:condition}).flexReload();
				    	return false;
				    },
				    cancelVal: '取消',
				    cancel: true 
			    });
			},
			cache:false
		});
	}
</script>

