<style>
/**点击筛选按钮时树节点不添加样式
.ztree li a span{
	color:#444;
}
**/
</style>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESDocumentBorrowing/js/menu.js"></script>
<div id='addrolefree'>
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span>
		<span class='w90 w14090 hei30'>比较符</span>
		<span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span>
		<!-- gengqianfeng 20140926 添加删除样式修改 -->
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">添加行</span></span>
		<span class='w90 w14090 hei30' style="text-align: center; margin-right: 0px; width: 60px;">删除行</span></span>
	</p>
	<div id='contents'>
		<!-- 1 -->
		<?php 
			for($fly=1;$fly<6;$fly++){
		?>
		<p class='contbox creatediv'  style="overflow:hidden;">
			<select name="esfields" class='w140 w14090 hei20 filedname'>
				<option value=''>请选择</option>
				<option value='borrowNum'>借阅单编号</option>
				<option value='borrowPerson'>借阅人</option>
				<option value='regDate'>登记日期</option>
				<option value='unit'>单位</option>
				<option value='telphone'>电话</option>
				<option value='eamil'>邮箱</option>
				<option value='overdueDays'>催还提前天数</option>
				<option value='regPerson'>登记人</option>
				<option value='status'>状态</option>
				<option value='idcardnum'>身份证</option>
				<option value='pnum'>件数</option>
				<option value='remark'>备注</option>
			</select>
			<select name="comparison" class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue' name="esfieldvalue"/>
			<select id='' class='w14090 w90 hei20 relationship' name="relation">
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<!-- gengqianfeng 20140926 添加删除样式修改 -->
			<a class='newfilter'></a><a class='delfilter'></a>
		</p>
		<?php }?>
	</div>
</div>
