<div id="eslist"   style="width: 650px;height:3250x;">
        <div class="find-dialog" style="margin-top: 8px;"><input id="userKeyWord" onblur="if($(this).val()=='')$(this).val('请输入关键字')" onfocus="if($(this).val()=='请输入关键字')$(this).val('')" type="text" name="userKeyWord" value="请输入关键字" /><span onclick="getUserQuery()"></span></div>
		<br><br><table id = "userGrid"></table>
 </div>
 <!--<input type="hidden" id="idstrHide" value="<?php echo $data;?>"/>-->
 <script type="text/javascript">
$(document).ready(function(){
	$("#userGrid").flexigrid({
		url : $.appClient.generateUrl({	ESDocumentBorrowing : 'findUserListByOrgid'}, 'x'),
		dataType : 'json',
		border:false,
		colModel : [ {
			display : '',
			name : 'startNum',
			width : 30,
			align : 'center'
		}, {
			display : '操作',
			name : 'ids',
			width : 40,
			sortable : true,
			align : 'center',
			metadata : 'ids',
		}, {
			display : 'ID',
			name : 'id',
			metadata : 'id',
			hide : true,
			align : 'center'
		}, {
			display : '用户名',
			name : 'userid',
			metadata : 'userid',
			width : 100,
			align : 'left'
		}, {
			display : '姓名',
			name : 'Name',
			metadata : 'Name',
			width : 100,
			sortable : true,
			align : 'left',
		}, {
			name : 'lastName',
			metadata : 'lastName',
			width : 50,
			sortable : true,
			align : 'left',
			hide : true
		}, {
			name : 'firstName',
			metadata : 'firstName',
			width : 80,
			sortable : true,
			align : 'left',
			hide : true
		}, {
			display : '状态',
			name : 'userStatus',
			metadata : 'userStatus',
			width : 30,
			sortable : true,
			align : 'center'
		}, {
			display : '手机',
			name : 'mobTel',
			metadata : 'mobTel',
			width : 100,
			sortable : true,
			align : 'left'
		}, {
			display : '邮件',
			name : 'emailAddress',
			metadata : 'emailAddress',
			width : 150,
			sortable : true,
			align : 'left',
			hide : true
		}, {
			display : '机构',
			name : 'orgname',
			metadata : 'orgname',
			width : 200,
			sortable : true,
			align : 'left'
		} ],
		singleSelect : true,
		usepager : true,
		useRp : true,
		rp : 20,
		nomsg : "没有数据",
		showTableToggleBtn : false,
		pagetext : '第',
		outof : '页 /共',
		pagestat : ' 显示 {from} 到 {to}条 / 共{total} 条'
	});
		
});

function getUserQuery(){
	var keyword=$.trim($('input[name="userKeyWord"]').val());
	if(keyword=='' || keyword=='请输入关键字') {
		keyword = '';
	}
	//var data = orgSeq+orgId;
	var url=$.appClient.generateUrl({ESDocumentBorrowing:'findUserListByOrgid',keyWord:encodeURI(keyword)},'x');
	$("#userGrid").flexOptions({url:url}).flexReload();
	return false;
}
//回车事件
$(document).keydown(function(event) {
    if (event.keyCode == 13 && document.activeElement.id == 'userKeyWord') {
    	getUserQuery();
    }
});
</script>
 